// <auto-generated />
using System;
using FoodAndDrinkRepository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodAndDrinkRepository.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512215050_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodAndDrinkRepository.Data.Entities.IngredientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Barcodes")
                        .HasColumnType("text[]");

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsHealthyOption")
                        .HasColumnType("boolean");

                    b.Property<string>("Macro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("UoM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Ingredients", (string)null);
                });

            modelBuilder.Entity("FoodAndDrinkRepository.Data.Entities.InventoryEntity", b =>
                {
                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserGroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("UoM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("IngredientId", "UserGroupId");

                    b.HasIndex("UserGroupId");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("FoodAndDrinkRepository.Data.Entities.MealEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<bool>("IsHealthyOption")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Meals", (string)null);
                });

            modelBuilder.Entity("FoodAndDrinkRepository.Data.Entities.MealIngredientEntity", b =>
                {
                    b.Property<Guid>("MealId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Preparation")
                        .HasColumnType("text");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("UoM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MealId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("MealIngredients", (string)null);
                });

            modelBuilder.Entity("FoodAndDrinkRepository.Data.Entities.MealPlanEntity", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MealSlot")
                        .HasColumnType("text");

                    b.Property<Guid>("UserGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MealId")
                        .HasColumnType("uuid");

                    b.HasKey("Date", "MealSlot", "UserGroupId");

                    b.HasIndex("MealId");

                    b.HasIndex("UserGroupId");

                    b.ToTable("MealPlan", (string)null);
                });

            modelBuilder.Entity("FoodAndDrinkRepository.Data.Entities.ShoppingListEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsManual")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("UserGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserGroupId");

                    b.ToTable("ShoppingLists", (string)null);
                });

            modelBuilder.Entity("FoodAndDrinkRepository.Data.Entities.ShoppingListIngredientEntity", b =>
                {
                    b.Property<Guid>("ShoppingListId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Purchased")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PurchasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("UoM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ShoppingListId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("ShoppingListIngredients", (string)null);
                });

            modelBuilder.Entity("FoodAndDrinkRepository.Data.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserGroupId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("FoodAndDrinkRepository.Data.Entities.UserGroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("UserGroups", (string)null);
                });

            modelBuilder.Entity("FoodAndDrinkRepository.Data.Entities.InventoryEntity", b =>
                {
                    b.HasOne("FoodAndDrinkRepository.Data.Entities.IngredientEntity", "Ingredient")
                        .WithMany("Inventory")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodAndDrinkRepository.Data.Entities.UserGroupEntity", "UserGroup")
                        .WithMany("Inventory")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("FoodAndDrinkRepository.Data.Entities.MealIngredientEntity", b =>
                {
                    b.HasOne("FoodAndDrinkRepository.Data.Entities.IngredientEntity", "Ingredient")
                        .WithMany("MealIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodAndDrinkRepository.Data.Entities.MealEntity", "Meal")
                        .WithMany("Ingredients")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("FoodAndDrinkRepository.Data.Entities.MealPlanEntity", b =>
                {
                    b.HasOne("FoodAndDrinkRepository.Data.Entities.MealEntity", "Meal")
                        .WithMany("MealPlanEntries")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FoodAndDrinkRepository.Data.Entities.UserGroupEntity", "UserGroup")
                        .WithMany("MealPlanEntries")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("FoodAndDrinkRepository.Data.Entities.ShoppingListEntity", b =>
                {
                    b.HasOne("FoodAndDrinkRepository.Data.Entities.UserGroupEntity", "UserGroup")
                        .WithMany("ShoppingLists")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("FoodAndDrinkRepository.Data.Entities.ShoppingListIngredientEntity", b =>
                {
                    b.HasOne("FoodAndDrinkRepository.Data.Entities.IngredientEntity", "Ingredient")
                        .WithMany("ShoppingListIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodAndDrinkRepository.Data.Entities.ShoppingListEntity", "ShoppingList")
                        .WithMany("Ingredients")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("FoodAndDrinkRepository.Data.Entities.UserEntity", b =>
                {
                    b.HasOne("FoodAndDrinkRepository.Data.Entities.UserGroupEntity", "UserGroup")
                        .WithMany("Users")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("FoodAndDrinkRepository.Data.Entities.IngredientEntity", b =>
                {
                    b.Navigation("Inventory");

                    b.Navigation("MealIngredients");

                    b.Navigation("ShoppingListIngredients");
                });

            modelBuilder.Entity("FoodAndDrinkRepository.Data.Entities.MealEntity", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("MealPlanEntries");
                });

            modelBuilder.Entity("FoodAndDrinkRepository.Data.Entities.ShoppingListEntity", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("FoodAndDrinkRepository.Data.Entities.UserGroupEntity", b =>
                {
                    b.Navigation("Inventory");

                    b.Navigation("MealPlanEntries");

                    b.Navigation("ShoppingLists");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
