import type { Metadata } from "next";
import "./globals.css";
import { Header } from "../components/Header";

export const metadata: Metadata = {
  title: "Food & Drink App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className="bg-neutral-content">
        <div className="min-h-screen mx-auto container bg-base-100">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
