import type { Metadata } from 'next'
import './globals.css'
import { Header } from '../components/Header'
import { FloatingActionButton } from '../components/FloatingActionButton'
import { ModalProvider } from '@/contexts/ModalContext'

export const metadata: Metadata = {
  title: 'Food & Drink App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className="bg-neutral-content">
        <ModalProvider>
          <div className="min-h-screen mx-auto container bg-base-100">
            <Header />
            {children}
            <FloatingActionButton />
          </div>
        </ModalProvider>
      </body>
    </html>
  )
}
