name: API Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'api/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./api
        file: ./api/Dockerfile
        push: false
        tags: api:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # - name: Export Docker image
    #   run: docker save api:latest | gzip > api-image.tar.gz

    # - name: Upload Docker image artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: api-docker-image
    #     path: api-image.tar.gz
    #     retention-days: 1
